name: Tests

on:
  push:
    branches: [master]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Build and test
    strategy:
      matrix:
        php: [7.2, 7.3, 7.4, 8.0]
        composer-flags: [""]
          -   php: 7.2
              composer-flags: --prefer-lowest

    steps:
      -   uses: actions/checkout@v2

      -   name: Set up PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: "${{ matrix.php }}"

      -   name: Install composer dependencies
          run: composer update ${{ matrix.composer-flags }}

      -   name: Run PHPUnit tests
          run: ./vendor/bin/phpunit -v
